# Generated by Django 6.0.2 on 2026-02-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Reservation',
        ),
    ]
